### ISSUE TITLE
General requests and suggestions for the Audio tab

### ISSUE THREAD

**Issue by BlackScreen** [WarmUpTill/SceneSwitcher#153]
Hello there,
I really love your OBS plug-in. It is simply the greatest addition to OBS there is - at least for me.
I am using it regularly and would love to have a few tweks, that would help my use cases very much. Maybe you can add those?

_Hide tabs_
I would love to hide tabs, which I do not use.
Maybe with a checkbox in the setup tab where the order of priority is selected?
This woul help and improve the UI greatly - at least for me.

_Save window size and position_
At the moment the window position and size is not saved.
It would help to improve my experience, because at the moment I have to resize the window every time.
The standard size is not enough for the sequence tab - which I use frequently.

_Improvements for Audio_
I could use a "force" or "override" rule in this tab. Or that the order of the defined rules is recognized.
For example to top one overrides the one below and so on. Probably a "force" checkbox would be more clear. I don't know.
My use case for this is, that one speaker should override every other rule - priority for the moderator.

Also I could use a cycle option in the audio tab to define a scene order when a signal is present.
For example I would define scene 1, then scene 2, then scene 3 and so on - with defined times. Much like in the sequence tab, just triggered from the audio tab. I know that this is possible right now, but maybe I could select a specific sequence (by number or by name - also a great add-on for the sequence tab maybe?) from the sequence tab?

These are my thoughts and use cases. Maybe you can have a look if some of these additions could be useful for others too.
Thank you for your time and effort you are putting into SceneSwitcher! :)

**Comment by WarmUpTill** [comment]
Hello,
thanks for the suggestions!

- Hide tabs
While hiding tabs is not possible at the moment you can move the tabs in any order you like.
So you could just move the tabs you use a lot to the front and the ones you rarely use to the back.

- Save window size and position
I will look into it.

- Improvements for Audio
I am not sure if I understand the purpose of "force" correctly.
The order in which the entries on the audio tab are evaluated already corresponds to the order of the elements in the UI.
So the top most entry has the highest priority.
The point regarding "scene order" is already implemented if I understood your suggestion correctly.
Have a look at the "Scene Group" tab. 
This will allow you to specify a group of scenes as the target for an entry on the Audio tab, which you can cycle through depending on certain conditions (count (probably not a good idea for the Audio tab), time or at random).

**Comment by BlackScreen** [comment]
>   While hiding tabs is not possible at the moment you can move the tabs in any order you like.
>   So you could just move the tabs you use a lot to the front and the ones you rarely use to the back.

I know this function and love it, so this is good.
But: The positions of the tabs are not saved either. I just checked on my running OBS, that had them a few hours ago in the order I wanted, now it is random. Maybe check this out, too. Would be great. :)

>   I am not sure if I understand the purpose of "force" correctly.
>   The order in which the entries on the audio tab are evaluated already corresponds to the order of the elements in the UI.
>   So the top most entry has the highest priority.

I will check this out properly. Thanks. The order could suffice.

>   Have a look at the "Scene Group" tab.
>   This will allow you to specify a group of scenes as the target for an entry on the Audio tab, which you can cycle through depending on certain conditions (count (probably not a good idea for the Audio tab), time or at random).

I will. Thanks! :)

**Comment by WarmUpTill** [comment]
> I know this function and love it, so this is good.
But: The positions of the tabs are not saved either. I just checked on my running OBS, that had them a few hours ago in the order I wanted, now it is random. Maybe check this out, too. Would be great. :)

That would be a bug and is not intended.
Which version of the plugin are you using?
Would you be able to send me your settings?

**Comment by BlackScreen** [comment]
Sure. I have attached the file for you to look at. This was saved, after the tabs were messed up. OBS was not closed in the 4 hours it took to mess them up.

[scene_switcher_backup_new.txt](https://github.com/WarmUpTill/SceneSwitcher/files/6215809/scene_switcher_backup_new.txt)

**Comment by WarmUpTill** [comment]
Hm, I don't see anything which should cause issues regarding the tab positions and can't reproduce any issues in that regard.
Can you give an example of which configuration does not save properly?

**Comment by BlackScreen** [comment]
> Can you give an example of which configuration does not save properly?

The configuration is saved properly. The window position and size is not saved or remembered at all - after closing the Scene Switcher window - and the tab positions were also not remembered correctly after leaving OBS open for a few hours. Relatively close to reordering - after closing - they are remembered correctly, but after about 4 hours they were back to the random order earlier today. It is a little weird and unconvenient, but not a show stopper.

**Comment by WarmUpTill** [comment]
Sorry I was a bit unclear - I was just referring to the tab positions.
Unfortunately I cannot explain how the tab positions are dependent on the run time of OBS.
Are you maybe running multiple instances of OBS?

The window size and position of the settings window is not saved at the moment.
So the behaviour of size and position not being restored is expected.

I implemented saving and loading of the window's geometry with https://github.com/WarmUpTill/SceneSwitcher/pull/154.
A first test build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/694009712

The option to enable / disable this new behaviour can be found on the General tab:
![SaveWindowGeo](https://user-images.githubusercontent.com/19472752/112739394-63e71900-8f74-11eb-9dad-896b4fe91f5d.PNG)

Let me know if this works as expected for you or if you run into any issues.

**Comment by BlackScreen** [comment]
> Are you maybe running multiple instances of OBS?

Nope, just the one.

> Let me know if this works as expected for you or if you run into any issues.

The new version with the window position and size is working fine for me, thank you for that. :)

**Comment by WarmUpTill** [comment]
I have found a bug which could lead to the tab order not saving and restoring properly, which could occur when switching between plugin versions, which have different amount of tabs available.
I will fix this with 8ae10debb026525354af9dcc7f50209401bee9ef.

Unfortunately your configuration does not seem to be affected and I am out of ideas what else could be causing issues on your end besides that.
Are you still facing the issue?
If not I would close this issue as the other topics were clarified.

If you disagree and there are still open points please let me know :)

**Comment by BlackScreen** [comment]
I have the problem still occurring and I just realized an option to "force" the problem.
I have two scene collections (hopefully this is the english name, I am using the german translation) and changed the order in the scene switcher window (with save windows position activated). It was saved in that scene and recalled after closing the window.
When I changed the collection, the order and window position was different (probably intended this way) and then, after I changed back to the original scene, the order was messed up. Weird.

**Comment by WarmUpTill** [comment]
It is indeed intended that different settings are loaded for each scene collection.
I cannot reproduce the issue on my end with a recent build - maybe the change mentioned above resolves the problem?
Would you be willing to give this a try?
A build including the change can be found here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/786684594

**Comment by BlackScreen** [comment]
Yes, with the new version the bug I described above is gone. Thanks!
I think you can probably close this then. :)

**Comment by WarmUpTill** [comment]
Thanks testing it!
